name: "Download cursed OIDC token"
description: "Download an unsafe OIDC token to ./oidc-token.txt. This is useful for sigstore conformance testing"

permissions: {}

runs:
  using: "composite"

  steps:
    - name: Download token
      run: |
        python $GITHUB_ACTION_PATH/download-token.py
      shell: bash
